<?php

// Main form_alter for instamotors
function instamotors_custom_form_alter(&$form, &$form_state, $form_id){
	if($form_id == 'motor_node_form'){
		$form['actions']['submit']['#submit'][] = 'instamotors_custom_submit';
	}
}

// Redirect user to their garage after edit/adding a new motor
function instamotors_custom_submit($form, &$form_state) {
	$form_state['redirect'] = array('user/'.$form_state['values']['uid'].'/garage');
}

// Search api ajax
function instamotors_custom_search_api_ajax_modules_alter(&$modules) {
  $modules[] = 'block';
}

/**
 * Implements hook_search_api_ajax_settings().
 */
function instamotors_custom_search_api_ajax_settings() {
  $settings = array(

    // required: CSS ID for the main content (search results html)
    'content' => '.span9 .view-im-searcher .view-content, .view-test .view-content',

    // required: array of regions with search-related blocks => CSS ID's
    'regions' => array(
      'my_region' => '.span9 #block-search-api-sorts-search-sorts',
      'sidebar_first' => '.span3 .region-sidebar-first',
      'sidebar_second' => '#sidebar-second',
    ),

    // optional: if you want to show a spinner image on AJAX
    'spinner' => drupal_get_path('module', 'search_api_ajax') .'/spinner.gif',

    // optional: if you want to scroll-back-to-top on paging search results
    'scrolltarget' => '#main-content',
    'scrollspeed' => 1000,

    // optional: fade main content on AJAX (fade=1 for true)
    'fade' => 1,
    'opacity' => 0.3,
  );

  return $settings;
}


/*function instamotors_custom_facet_items_alter(&$build, &$settings) {


  if ($settings->facet == "YOUR_FACET_NAME") {
    foreach($build as $key => $item) {
      $build[$key]["#path"] = 'hello';
    }
  }

  dpm($settings);
  dpm($build);
}
*/

// http://www.im.com/search_api_ajax/im-search/field_car_price/%5B1000%20TO%202000%5D
// http://www.im.com/im-search?search_api_views_fulltext=&f[0]=field_car_price/%5B1000%20TO%202000%5D

// http://www.im.com/im-search/field_car_price/%5B2000%20TO%203000%5D
//http://www.im.com/im-search/field_car_colour/blue-8?search_api_views_fulltext=
